### ISSUE TITLE
Add the ability to ignore certain UPROPERTY

### ISSUE THREAD

**Issue by afuzzyllama** [afuzzyllama/DataAccess#1]
Right now the queries are being built off all UPROPERTYs in the UCLASS.  It is possible to add meta information like meta=(SaveToDatabase = "true") and have the building of queries ignore properties that do not have that meta data.  The change shouldn't be too hard to implement, just needs to be done and the test needs to pass in the session frontend.

**Comment by afuzzyllama** [comment]
Implemented.  All uproperty need SaveToDatabase="true" in the meta part of the UPROPERTY()

**Comment by HiddenFox** [comment]
Currently, Property->HasMetaData can only be called with "#if WITH_EDITOR". How to use this feature in Non-Editor builds?

**Comment by afuzzyllama** [comment]
I'm not sure.  It is possible that was added after I stopped working on this repo.  Would probably take some research to figure out a work around.
